browser: Firefox
position:
  x: 0
  y: 0
dimension:
  width: 1366
  height: 768
urls:
  signin: account.daocloud.co/signin
  dashboard: 'dashboard.daocloud.co'
  buildflow: 'dashboard.daocloud.co/build-flows'
user:
  username: CaptainDao
  password: dangerous
screenshot:
  dir: images
  wait: 3
